name: Trigger auto deployment for face-based-photo-segregation

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/face-based-photo-segregation-AutoDeployTrigger-3263f19e-89e9-443b-8f22-bfeb129d0f2f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FACEBASEDPHOTOSEGREGATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FACEBASEDPHOTOSEGREGATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FACEBASEDPHOTOSEGREGATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.FACEBASEDPHOTOSEGREGATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FACEBASEDPHOTOSEGREGATION_REGISTRY_PASSWORD }}
          containerAppName: face-based-photo-segregation
          resourceGroup: Face_based_Photo_Segregation
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


